---
- name: Include Ubuntu release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"

- name: install squid
  apt:
    pkg: "{{ squid_packages }}"
    state: present

- name: copy app config
  template: src=squid.conf.j2 dest={{ squid_config_dir }}/squid.conf owner=root group=root mode=0644
  notify: restart squid

- meta: flush_handlers

- name: ensure squid started and startup
  service: name={{ squid_service }} state=started enabled=yes

- name: add nghttpx ppa
  apt_repository: repo='ppa:ondrej/apache2' state=present update_cache=yes

- name: install nghttpx
  apt: pkg=nghttp2-proxy state=present update_cache=yes cache_valid_time=86400

- name: ensure nghttpx log path exists
  file: path=/var/log/nghttpx state=directory owner=root group=root mode=0755

- name: Ensures cert dir exists
  file: path={{ nghttpx_certs_path }} state=directory owner=root group=root mode=0755

- name: upload priviate key as file
  copy: src={{ nghttpx_local_private_key_path }} dest={{ nghttpx_private_key_path }} owner=root group=root mode=0644
  when: nghttpx_local_private_key_path is defined
  notify: restart nghttpx

- name: upload cert as file
  copy: src={{ nghttpx_local_certificate_path }} dest={{ nghttpx_certificate_path }} owner=root group=root mode=0644
  when: nghttpx_local_certificate_path is defined
  notify: restart nghttpx

- name: upload priviate key as data
  copy: content={{ nghttpx_local_private_key_data }} dest={{ nghttpx_private_key_path }} owner=root group=root mode=0644
  when: nghttpx_local_private_key_data is defined
  notify: restart nghttpx

- name: upload cert as file
  copy: content={{ nghttpx_local_certificate_data }} dest={{ nghttpx_certificate_path }} owner=root group=root mode=0644
  when: nghttpx_local_certificate_data is defined
  notify: restart nghttpx

- name: copy nghttpx config
  template: src=nghttpx.conf.j2 dest=/etc/nghttpx/nghttpx.conf owner=root group=root mode=0644
  notify: restart nghttpx

- meta: flush_handlers

- name: ensure nghttpx started and startup
  service: name=nghttpx state=started enabled=yes
